version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt-get update
      - sudo apt-get install nginx -y

  build:
    commands:
      - echo Build started on `date`
      - mkdir -p output/scripts
      - cp index.html output/
      - cp appspec.yml output/
      - cp -r scripts/* output/scripts

  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - output/**/*
